### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by ellisonpatterson** [Lavoaster/IPS-SteamLoginMethod#104]
```OutOfRangeException:  (0)
#0 /home/ipboard/public_html/mainsite/applications/core/sources/ProfileSync/Steam.php(33): IPS\Patterns\_ActiveRecord::load('steam')
#1 /home/ipboard/public_html/mainsite/applications/core/sources/ProfileSync/Steam.php(71): IPS\core\ProfileSync\_Steam->userData()
#2 /home/ipboard/public_html/mainsite/applications/core/sources/ProfileSync/ProfileSyncAbstract.php(243): IPS\core\ProfileSync\_Steam->photo()
#3 /home/ipboard/public_html/mainsite/system/Login/Steam.php(152): IPS\core\ProfileSync\_ProfileSyncAbstract->sync()
#4 /home/ipboard/public_html/mainsite/system/Login/LoginAbstract.php(112): IPS\Login\_Steam->authenticate(Object(IPS\Http\Url\Friendly))
#5 /home/ipboard/public_html/mainsite/system/Login/Login.php(293): IPS\Login\_LoginAbstract->authenticateButton(Object(IPS\Login))
#6 /home/ipboard/public_html/mainsite/applications/core/modules/front/system/login.php(48): IPS\_Login->authenticate()
#7 /home/ipboard/public_html/mainsite/system/Dispatcher/Controller.php(96): IPS\core\modules\front\system\_login->manage()
#8 /home/ipboard/public_html/mainsite/system/Dispatcher/Dispatcher.php(146): IPS\Dispatcher\_Controller->execute()
#9 /home/ipboard/public_html/mainsite/index.php(13): IPS\_Dispatcher->run()
#10 {main}```

**Comment by madman32395** [comment]
4.3 changed the way ProfileSync is handled.

**Comment by madman32395** [comment]
#102 ; profile sync

**Comment by Lavoaster** [comment]
Please download [this](https://github.com/Lavoaster/IPS-SteamLoginMethod/releases/download/v3.0.0/steamlogin-3.0.0.zip) and follow the instructions in the readme for upgrading.
